package com.example.waiuscheduler.database.tables;

import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import java.util.Date;

/// Entity for assessment table
@Entity(tableName = "assessment",
        foreignKeys = @ForeignKey(
                entity = PaperEntity.class,      // Class of foreign key
                parentColumns = "paperId",      // Foreign key variable
                childColumns = "paperId_fk",    // Foreign key name
                onDelete = ForeignKey.CASCADE   // Dependency on paper
        ),
        indices = {@Index("paperId_fk")}        // Index of the foreign key
)
public class AssessmentEntity {
    @PrimaryKey(autoGenerate = true)
    private int assessmentId;    // Unique id for assessments
    private String title;           // Title for the assessment
    private Date dueDate;         // Due date of the assessment
    private Double weight;          // Weight of marks for the assessment
    private String type;            // Type of assessment (eg. test, assessment, exam)
    private Double grade;           // Grade given on assessment
    private String paperId_fk;     // Foreign key to reference the paper table

    /// Constructor for the paper table
    /// @param title The title of the assessment
    /// @param dueDate The due date of the assessment
    /// @param weight The percentage of the grade the assessment is worth
    /// @param type The type of assessment the assessment is
    /// @param grade The grade received after completing the assessment
    /// @param paperId_fk Foreign key for which paper the assessment is for
    public AssessmentEntity(String title, Date dueDate, Double weight,
                            String type, Double grade, String paperId_fk) {
        this.title = title;
        this.dueDate = dueDate;
        this.weight = weight;
        this.type = type;
        this.grade = grade;
        this.paperId_fk = paperId_fk;
    }

    /// Set assessment Id
    /// @param assessmentId Autogenerated primary key for an assessment
    public void setAssessmentId(int assessmentId) {
        this.assessmentId = assessmentId;
    }

    /// Get assessment Id
    /// @return Autogenerated primary key for an assessment
    public int getAssessmentId() {
        return assessmentId;
    }

    /// Get assessment title
    /// @return Title of the assessment
    public String getTitle() {
        return title;
    }
    
    /// Set assessment title
    /// @param title Title of the assessment
    public void setTitle(String title) {
        this.title = title;
    }

    /// Get assessment due date
    /// @return Date the assessment is due
    public Date getDueDate() {
        return dueDate;
    }
    
    /// Set assessment due date
    /// @param dueDate Date the assessment is due
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /// Get the weight of the assessment
    /// @return The weight of the grade the assessment is worth
    public Double getWeight() {
        return weight;
    }
    
    /// Set the weight of the assessment
    /// @param weight The weight of the grade the assessment is worth
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /// Get the type of the assessment
    /// @return The type of the assessment (eg. assignment, test)
    public String getType() {
        return type;
    }

    /// Set the type of the assessment
    /// @param type The type of assessment
    public void setType(String type) {
        this.type = type;
    }

    /// Get the grade achieved in the assessment
    /// @return The grade achieved or 0 if not inputted in the assessment
    public Double getGrade() {
        return grade;
    }

    /// Set the grade achieved in the assessment
    /// @param grade The grade achieved in the assessment
    public void setGrade(Double grade) {
        this.grade = grade;
    }

    /// Get the paper Id foreign key
    /// @return The paper Id that the assessment is for
    public String getPaperId_fk() {
        return paperId_fk;
    }

    /// Get the paper Id foreign key
    /// @param paperId_fk The paper id the assessment is for
    public void setPaperId_fk(String paperId_fk) {
        this.paperId_fk = paperId_fk;
    }
}
