package com.example.waiuscheduler.database.tables;

import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import java.util.Date;


/// Entity for event table
@Entity(tableName = "event",
        foreignKeys = @ForeignKey(
                entity = TimetablePatternEntity.class,   // Class of foreign key
                parentColumns = "type",          // Foreign key variable
                childColumns = "timetableId_fk",        // Foreign key name
                onDelete = ForeignKey.CASCADE           // Dependency on timetable
        ),
        indices = {@Index("timetableId_fk")}            // Index of the foreign key
)
public class EventEntity {
    @PrimaryKey(autoGenerate = true)
    private int eventId;     // Unique identifier for the event
    private Date dateTimeStart;   // Start time
    private Date dateTimeEnd;     // End time
    private Boolean attended;       // Monitor attendance of each event
    private String timetableId_fk;     // Foreign key references the timetable table

    /// Constructor for the event table
    /// @param dateTimeStart Date and time the event starts
    /// @param dateTimeEnd Date and time the event ends
    /// @param attended Whether the user attended the event
    /// @param timetableId_fk Foreign key for the timetable occurance the event is
    public EventEntity(Date dateTimeStart,
                       Date dateTimeEnd, Boolean attended, String timetableId_fk
    ) {
        this.dateTimeStart = dateTimeStart;
        this.dateTimeEnd = dateTimeEnd;
        this.attended = attended;
        this.timetableId_fk = timetableId_fk;
    }

    /// Set event Id
    /// @param eventId Autogenerated primary key for the event
    public void setEventId(int eventId) {
        this.eventId = eventId;
    }

    /// Get event Id
    /// @return The autogenerated primary key for the event
    public int getEventId() {
        return eventId;
    }

    /// Get when the event starts
    /// @return The date and time of the event start
    public Date getDateTimeStart() {
        return dateTimeStart;
    }

    /// Set when the event starts
    /// @param dateTimeStart The date and time of the event start
    public void setDateTimeStart(Date dateTimeStart) {
        this.dateTimeStart = dateTimeStart;
    }

    /// Get when the event ends
    /// @return The date and time of the event end
    public Date getDateTimeEnd() {
        return dateTimeEnd;
    }

    /// Set when the event ends
    /// @param dateTimeEnd The date and time of the event end
    public void setDateTimeEnd(Date dateTimeEnd) {
        this.dateTimeEnd = dateTimeEnd;
    }

    /// Get if the event was attended
    /// @return Attendance of the event
    public Boolean getAttended() {
        return attended;
    }

    /// Set if the event was attended
    /// @param attended Whether the event was attended
    public void setAttended(Boolean attended) {
        this.attended = attended;
    }

    /// Get the timetable pattern foreign key
    /// @return The timetable pattern id for the event occurrence
    public String getTimetableId_fk() {
        return timetableId_fk;
    }

    /// Set the timetable pattern foreign key
    /// @param timetableId_fk The timetable pattern id for the event occurrence
    public void setTimetableId_fk(String timetableId_fk) {
        this.timetableId_fk = timetableId_fk;
    }
}
