package com.example.waiuscheduler.database.tables;

import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import java.util.Date;

/// Entity for study session table
@Entity(tableName = "study_session",
        foreignKeys = @ForeignKey(
                entity = PaperEntity.class,  // Class of foreign key
                parentColumns = "paperId",  // Foreign key variable
                childColumns = "paperId_fk",    // Foreign key name
                onDelete = ForeignKey.CASCADE   // Dependency on paper
        ),
        indices = {@Index("paperId_fk")}
)
public class StudySessionEntity {
    @PrimaryKey(autoGenerate = true)        // Unique Id for the study session
    private int sessionId;
    private Date dateTimeStart;           // Start time of study session
    private Date dateTimeEnd;             // End time of study session
    private Double duration;                // Duration of study session
    private String notes;                   // Notes from session
    private String paperId_fk;          // Foreign key referencing paper

    /// Constructor for the study session table
    /// @param dateTimeStart Start date and time as the study session
    /// @param dateTimeEnd  End date and time as the study session
    /// @param duration Length of study session
    /// @param notes Additional user input for the session
    /// @param paperId_fk The id for the paper being studied for
    public StudySessionEntity(Date dateTimeStart, Date dateTimeEnd, Double duration,
                              String notes, String paperId_fk) {
        this.dateTimeStart = dateTimeStart;
        this.dateTimeEnd = dateTimeEnd;
        this.duration = duration;
        this.notes = notes;
        this.paperId_fk = paperId_fk;
    }

    /// Get study session id
    /// @return Autogenerated session id
    public int getSessionId() {
        return sessionId;
    }

    /// Set study session id
    /// @param sessionId Autogenerated session id
    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }

    /// Get when the study session started
    /// @return Date and time of the start of the session
    public Date getDateTimeStart() {
        return dateTimeStart;
    }

    /// Set when the study session started
    /// @param dateTimeStart Date and time of the start of the session
    public void setDateTimeStart(Date dateTimeStart) {
        this.dateTimeStart = dateTimeStart;
    }

    /// Get when the study session ended
    /// @return Date and time of the end of the session
    public Date getDateTimeEnd() {
        return dateTimeEnd;
    }

    /// Set when the study session ended
    /// @param dateTimeEnd Date and time of the end of the session
    public void setDateTimeEnd(Date dateTimeEnd) {
        this.dateTimeEnd = dateTimeEnd;
    }

    /// Get the duration of the study session
    /// @return Length of study session in minutes
    public Double getDuration() {
        return duration;
    }

    /// Set the duration of the study session
    /// @param duration Length of study session in minutes
    public void setDuration(Double duration) {
        this.duration = duration;
    }

    /// Get study session notes
    /// @return Additional notes from the user
    public String getNotes() {
        return notes;
    }

    /// Set study session notes
    /// @param notes Additional notes from the user
    public void setNotes(String notes) {
        this.notes = notes;
    }

    /// Get paper id assigned for the session
    /// @return Foreign key paper id
    public String getPaperId_fk() {
        return paperId_fk;
    }

    /// Set paper id assigned for the study session
    /// @param paperId_fk Foreign key paper id
    public void setPaperId_fk(String paperId_fk) {
        this.paperId_fk = paperId_fk;
    }
}
